# Swin-UNet模型配置
# 基于Swin Transformer的U-Net架构

name: "SwinUNet"

params:
  in_channels: 1
  out_channels: 1
  img_size: 128
  
  kwargs:
    # Swin Transformer参数
    patch_size: 4
    window_size: 8
    depths: [2, 2, 6, 2]        # 每个stage的层数
    num_heads: [3, 6, 12, 24]   # 每个stage的注意力头数
    embed_dim: 96               # 嵌入维度
    mlp_ratio: 4.0              # MLP隐藏层倍数
    
    # Dropout配置
    drop_rate: 0.0
    attn_drop_rate: 0.0
    drop_path_rate: 0.1
    
    # 激活函数
    norm_layer: "LayerNorm"
    
    # 上采样方式
    upsample_mode: "bilinear"   # bilinear, nearest, transpose_conv
    
    # 跳跃连接
    use_skip_connections: true
    
    # 可选FNO瓶颈
    use_fno_bottleneck: false
    fno_modes: 16