# UNet模型配置
# 经典U-Net架构

name: "UNet"

params:
  in_channels: 1
  out_channels: 1
  img_size: 128
  
  kwargs:
    # U-Net结构参数
    base_channels: 64       # 基础通道数
    channel_multipliers: [1, 2, 4, 8]  # 每层通道倍数
    num_res_blocks: 2       # 每层残差块数量
    
    # 注意力机制
    attention_resolutions: [16, 8]  # 使用注意力的分辨率
    num_heads: 8            # 注意力头数
    
    # 激活函数和归一化
    activation: "swish"     # swish, relu, gelu
    norm: "group"           # batch, group, layer
    num_groups: 32          # GroupNorm组数
    
    # Dropout
    dropout: 0.0
    
    # 上采样方式
    upsample_mode: "bilinear"  # bilinear, nearest, transpose_conv
    
    # 跳跃连接
    use_skip_connections: true
    
    # 可选参数
    use_self_attention: true
    use_checkpoint: false   # 梯度检查点