# U-Net++模型配置
# 嵌套U-Net架构，通过密集跳跃连接改进标准U-Net

name: "UNetPlusPlus"

params:
  in_channels: 1
  out_channels: 1
  img_size: 128
  
  kwargs:
    features: [32, 64, 128, 256, 512]  # 特征通道数列表
    deep_supervision: false            # 是否启用深度监督
    dropout: 0.0                      # Dropout概率

# 模型特点
description: |
  U-Net++是嵌套U-Net架构，主要特点：
  - 密集跳跃连接：减少编码器和解码器特征图之间的语义差距
  - 嵌套路径：每个节点接收来自所有先前节点的特征
  - 可选深度监督：在不同深度级别进行监督学习
  - 渐进式特征融合：逐步细化特征表示

# 适用场景
use_cases:
  - 医学图像分割
  - 高精度图像重建
  - 需要精细边界的任务
  - 多尺度特征融合场景