# 裁剪任务配置 - 20%观测

# 继承基础训练配置
defaults:
  - /train

# 任务特定配置
data:
  task: "Crop"
  task_params:
    crop_ratio: 0.2  # 20%观测
    crop_strategy: "mixed"
    crop_sampling:
      uniform_ratio: 0.4      # 均匀采样40%
      boundary_ratio: 0.3     # 边界采样30%
      high_gradient_ratio: 0.3 # 高梯度采样30%
    boundary_mode: "mirror"
    boundary_width: 16

# 20%观测更困难，需要更多训练
training:
  epochs: 250
  batch_size: 6  # 减小batch size
  
  optimizer:
    params:
      lr: 1.0e-3  # 降低学习率
      
  scheduler:
    params:
      T_max: 250
      warmup_steps: 1250

# 损失函数权重调整
loss:
  rec_weight: 1.0
  spec_weight: 0.6  # 增加频域约束
  dc_weight: 1.5    # 增强数据一致性

# 实验命名
experiment:
  name_template: "Crop20-{data}-{res}-{model}-s{seed}-{date}"