# @package _global_

# 默认配置文件
defaults:
  - data: pdebench
  - model: swin_unet
  - train: default
  - _self_

# 实验配置
experiment:
  name: "SRx4-DR2D-128-SwinUNet-s2025"
  seed: 2025
  device: "cuda"
  precision: 16  # AMP混合精度
  use_amp: true  # 启用混合精度训练
  output_dir: "runs/${experiment.name}"

# 输出路径
output_dir: "runs/${experiment.name}"
checkpoint_dir: "${output_dir}/checkpoints"
log_dir: "${output_dir}/logs"

# Hydra配置
hydra:
  run:
    dir: ${output_dir}
  job:
    chdir: true