# Vision Transformer (ViT) 训练配置
# 基于标准训练配置，适配ViT模型

defaults:
  - data: pdebench
  - model: vit
  - train: default
  - _self_

# 数据配置
data:
  data_path: "E:/2D/DarcyFlow/2D_DarcyFlow_beta1.0_Train.hdf5"
  dataset_name: "PDEBench"
  keys: ["tensor"]  # 数据变量键名
  splits_dir: "splits"
  image_size: 128
  
  # 观测配置
  observation:
    mode: "SR"  # SR (超分辨率) 或 Crop (裁剪)
    sr:
      scale_factor: 4
      blur_sigma: 1.0
      blur_kernel_size: 5
      boundary_mode: "mirror"
    crop:
      crop_size: [64, 64]
      crop_strategy: "uniform"  # uniform, boundary, high_gradient
      boundary_mode: "mirror"
  
  # 预处理配置
  preprocessing:
    normalize: true
    cache_data: false
  
  # 数据加载器配置
  dataloader:
    batch_size: 4  # 适中批次大小，适应1000样本训练集
    num_workers: 4
    pin_memory: true
    persistent_workers: true

# 实验配置
experiment:
  name: "SRx4-DR2D-128-ViT-s2025"
  seed: 2025
  device: "cuda"
  precision: 16  # AMP混合精度
  use_amp: true  # 启用混合精度训练
  output_dir: "runs/${experiment.name}"

# 模型配置
model:
  name: "ViT"  # ViT模型
  params:
    in_channels: 1
    out_channels: 1
    img_size: 128
    patch_size: 16
    embed_dim: 768
    encoder_depth: 12
    encoder_num_heads: 12
    encoder_mlp_ratio: 4.0
    decoder_depth: 4
    decoder_num_heads: 8
    decoder_mlp_ratio: 4.0
    dropout: 0.1
    attention_dropout: 0.1
    stochastic_depth: 0.1

# 训练配置
training:
  epochs: 200
  batch_size: 4
  
  # 优化器配置
  optimizer:
    name: "AdamW"
    params:
      lr: 0.001
      weight_decay: 0.0001
      betas: [0.9, 0.999]
      eps: 1e-8
  
  # 学习率调度器
  scheduler:
    name: null
  
  # 梯度裁剪
  grad_clip_norm: 1.0  # 标准梯度裁剪
  
  # 日志和保存
  log_interval: 50
  save_interval: 20
  plot_interval: 50
  
  # 混合精度训练
  use_amp: true

# 损失函数配置 - 按照技术架构文档标准
loss:
  # 权重配置（三件套标准：1.0/0.5/1.0）
  rec_weight: 1.0      # L_rec权重（文档标准）
  spec_weight: 0.5     # L_spec权重（文档标准）
  dc_weight: 1.0       # L_dc权重（文档标准）
  
  # 损失类型
  rec_loss_type: "l2"    # l1, l2, huber, smooth_l1
  spec_loss_type: "l2"   # l1, l2
  dc_loss_type: "l2"     # l1, l2
  
  # 频域损失参数 - 按照文档标准
  low_freq_modes: 16  # 低频模式数量 kx=ky=16（文档标准）
  mirror_padding: true  # 启用镜像延拓（非周期边界）

# 输出路径
output_dir: "runs/${experiment.name}"
checkpoint_dir: "${output_dir}/checkpoints"
log_dir: "${output_dir}/logs"

# 日志配置
logging:
  level: "INFO"
  use_tensorboard: true
  use_wandb: false
  wandb_project: "pdebench-sparse2full"

# Hydra配置
hydra:
  run:
    dir: ${output_dir}
  job:
    chdir: true