# 训练配置文件
# PDEBench稀疏观测重建系统

defaults:
  - _self_

# 实验配置
experiment:
  name: "pdebench_sr_x4"
  device: "cuda:0"
  seed: 2025
  output_dir: "runs"

# 数据配置
data:
  data_path: "E:/2D/DarcyFlow/2D_DarcyFlow_beta1.0_Train.hdf5"
  dataset_name: "PDEBench"
  keys: ["tensor"]  # 数据变量键名
  splits_dir: "splits"
  image_size: 128
  
  # 观测配置
  observation:
    mode: "SR"  # SR (超分辨率) 或 Crop (裁剪)
    sr:
      scale_factor: 4
      blur_sigma: 1.0
      blur_kernel_size: 5
      boundary_mode: "mirror"
    crop:
      crop_size: [64, 64]
      crop_strategy: "uniform"  # uniform, boundary, high_gradient
      boundary_mode: "mirror"
  
  # 预处理配置
  preprocessing:
    normalize: true
    cache_data: false
  
  # 数据加载器配置
  dataloader:
    batch_size: 4  # 适中批次大小，适应1000样本训练集
    num_workers: 4
    pin_memory: true
    persistent_workers: true

# 模型配置
model:
  name: "SwinUNet"  # SwinUNet, Hybrid, MLP
  params:
    in_channels: 1
    out_channels: 1
    img_size: 128
    kwargs:
      # SwinUNet特定参数
      patch_size: 4
      window_size: 8
      depths: [2, 2, 6, 2]
      num_heads: [3, 6, 12, 24]
      embed_dim: 96
      mlp_ratio: 4.0
      drop_rate: 0.0
      attn_drop_rate: 0.0
      drop_path_rate: 0.1

# 训练配置
training:
  epochs: 200
  batch_size: 4  # 适中批次大小，适应1000样本训练集
  seed: 2025
  output_dir: "runs"
  
  # 优化器配置 - 按照技术架构文档标准
  optimizer:
    name: "AdamW"
    params:
      lr: 1.0e-4  # 适中学习率，适应更大数据集
      weight_decay: 1.0e-4
      betas: [0.9, 0.999]
  
  # 学习率调度器 - 按照技术架构文档标准（Cosine+1k warmup）
  scheduler:
    name: "cosine_warmup"
    params:
      T_max: 200
      warmup_steps: 1000  # 1k warmup（文档标准）
      eta_min: 1.0e-6
  
  # 梯度裁剪
  grad_clip_norm: 1.0  # 标准梯度裁剪
  
  # 日志和保存
  log_interval: 50
  save_interval: 20
  plot_interval: 50
  
  # 混合精度训练
  use_amp: true

# 损失函数配置 - 按照技术架构文档标准
loss:
  # 权重配置（三件套）
  rec_weight: 1.0      # L_rec权重
  spec_weight: 0.0     # L_spec权重 - 完全禁用频域损失以解决NaN问题
  dc_weight: 0.0       # L_dc权重 - 暂时禁用DC损失以隔离问题
  
  # 损失类型
  rec_loss_type: "l2"    # l1, l2, huber, smooth_l1
  spec_loss_type: "l2"   # l1, l2
  dc_loss_type: "l2"     # l1, l2
  
  # 频域损失参数
  low_freq_modes: 4  # 进一步降低频域模式数
  mirror_padding: false  # 禁用镜像延拓以避免数值不稳定
  
  # 可选损失
  use_gradient_loss: false
  gradient_weight: 0.1
  
  use_pde_residual_loss: false
  pde_residual_weight: 0.1
  pde_low_freq_weight: 2.0

# 验证配置
validation:
  batch_size: 8  # 适中验证批次大小
  metrics:
    - "rel_l2"
    - "mae" 
    - "psnr"
    - "ssim"
    - "frmse_low"
    - "frmse_mid"
    - "frmse_high"

# 设备配置
device:
  use_cuda: true
  cuda_device: 0
  num_workers: 4
  pin_memory: true

# 日志配置
logging:
  level: "INFO"
  use_tensorboard: true
  use_wandb: false
  wandb_project: "pdebench-sparse2full"
  
# 可复现性配置
reproducibility:
  deterministic: true
  benchmark: false