# @package train

# Crop任务课程学习训练配置
# 先大窗后小窗的渐进式训练策略

# 基础训练参数
num_epochs: 200
batch_size: 8
learning_rate: 1e-3
weight_decay: 1e-4

# 课程学习配置
curriculum_learning:
  enabled: true
  stages:
    # 第一阶段：大窗口训练（40%覆盖率）
    - name: "large_window"
      epochs: 80
      crop_coverage: 0.4  # 40%覆盖率
      crop_size: [102, 102]  # 约40%的256×256
      learning_rate: 1e-3
      batch_size: 12
      
    # 第二阶段：中等窗口训练（30%覆盖率）
    - name: "medium_window"
      epochs: 60
      crop_coverage: 0.3  # 30%覆盖率
      crop_size: [89, 89]  # 约30%的256×256
      learning_rate: 7e-4
      batch_size: 10
      load_from_previous: true
      
    # 第三阶段：小窗口训练（20%覆盖率）
    - name: "small_window"
      epochs: 60
      crop_coverage: 0.2  # 20%覆盖率
      crop_size: [72, 72]  # 约20%的256×256
      learning_rate: 5e-4
      batch_size: 8
      load_from_previous: true

# 采样策略配置
sampling_strategy:
  # 混合采样：均匀40% + 边界30% + 高梯度30%
  uniform_ratio: 0.4
  boundary_ratio: 0.3
  high_gradient_ratio: 0.3
  
  # 边界采样参数
  boundary_width: 16  # 边界带宽度（像素）
  
  # 高梯度采样参数
  gradient_threshold: 0.1  # 梯度阈值
  gradient_kernel_size: 3  # 梯度计算核大小

# 优化器配置
optimizer:
  type: "adamw"
  lr: ${training.learning_rate}
  weight_decay: ${training.weight_decay}
  betas: [0.9, 0.999]
  eps: 1e-8

# 学习率调度
scheduler:
  type: "cosine"
  warmup_steps: 1000
  min_lr: 1e-6
  restart_epochs: []

# 混合精度训练
amp:
  enabled: true
  opt_level: "O1"
  loss_scale: "dynamic"

# 梯度处理
gradient:
  clip_norm: 1.0
  accumulation_steps: 1

# 早停策略
early_stopping:
  patience: 15  # Crop任务可能需要更多耐心
  monitor: "val_rel_l2"
  mode: "min"
  min_delta: 1e-4

# 检查点保存
checkpoint:
  save_top_k: 3
  monitor: "val_rel_l2"
  mode: "min"
  save_last: true
  every_n_epochs: 10

# 验证配置
validation:
  check_val_every_n_epoch: 1
  val_check_interval: 1.0

# 日志配置
logging:
  log_every_n_steps: 50
  log_gpu_memory: true
  
# 数据增强（Crop任务特定）
data_augmentation:
  enabled: true
  flip_prob: 0.5
  rotate_prob: 0.3
  rotate_angles: [90, 180, 270]
  
  # Crop特定增强
  crop_jitter:
    enabled: true
    max_shift: 8  # 最大偏移像素
    prob: 0.3
    
  # 多尺度训练
  multiscale_training:
    enabled: true
    scales: [0.8, 1.0, 1.2]  # 相对于基础crop_size的缩放
    prob: 0.2